---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
#  - name: debian-8
#  - name: debian-9
  - name: ubuntu-18.04
  - name: centos-7
#  - name: fedora-26
  - name: fedora-27
#  - name: fedora-28

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
